/*
 * This file was autogenerated by the Lingua Franca Compiler.
 *
 * Source: file:/home/ali123ata/Desktop/3/Tinification/castfunction_variables/castfunction_variables.lf
 */

#include "reactor-cpp/reactor-cpp.hh"

#include "castfunction_variables/_lf_preamble.hh"

using namespace std::chrono_literals;
using namespace reactor::operators;

            
