/*
 * This file was autogenerated by the Lingua Franca Compiler.
 *
 * Source: file:/home/marziyeh/tinification/Tinification/TinyTwinGenerator/castfunction_variables/castfunction_variables.lf
 */

#pragma once

#include <vector>
#include <array>

#include "reactor-cpp/reactor-cpp.hh"
// include the preambles from imported files 
#include "castfunction_variables/_lf_preamble.hh"

using namespace std::chrono_literals;

            
