/*
 * This file was autogenerated by the Lingua Franca Compiler.
 *
 * Source: file:/home/vboxuser/Downloads/tinification/MyExample/extraction_function/extraction_function.lf
 */

#pragma once

#include <vector>
#include <array>

#include "reactor-cpp/reactor-cpp.hh"
// include the preambles from imported files 
#include "extraction_function/_lf_preamble.hh"

using namespace std::chrono_literals;

            
