/*
 * This file was autogenerated by the Lingua Franca Compiler.
 *
 * Source: file:/home/vboxuser/Downloads/MyExample%20(copy)/Tinification/extraction_function/extraction_function.lf
 */

#include "extraction_function/extraction_function.hh"

using namespace reactor::operators;

  // private preamble
  #include <fstream>
  #include <vector>
  #include <string>
  #include <iostream>
  #include <stdio.h>
  #include <string>

// outer constructor
extraction_function::extraction_function(const std::string& name, reactor::Environment* __lf_environment, Parameters&& __lf_parameters)
  : reactor::Reactor(name, __lf_environment)
  , __lf_inner(this, std::forward<Parameters>(__lf_parameters))
  //reactor instances
  // timers
  // actions
  
  // reaction views
  
{
            
            
  // reaction views
  
}
extraction_function::extraction_function(const std::string& name, reactor::Reactor* __lf_container, Parameters&& __lf_parameters)
  : reactor::Reactor(name, __lf_container)
  , __lf_inner(this, std::forward<Parameters>(__lf_parameters))
  //reactor instances
  // timers
  // actions
  
  // reaction views
  
{
            
            
  // reaction views
  
}

// inner constructor
extraction_function::Inner::Inner(::reactor::Reactor* reactor, Parameters&& parameters)
  : LFScope(reactor)
  , __lf_parameters(std::forward<Parameters>(parameters))
  // state variables
{}

void extraction_function::assemble() {
  // reaction_1
  reaction_1.declare_trigger(&startup);
          
          
  // connections
}

// methods


// reaction reaction_1

void extraction_function::Inner::reaction_1([[maybe_unused]] const reactor::StartupTrigger& startup) {
        std::ifstream readFile;
  std::fstream writeFile;
  
  
  //std::cout << "Please enter your file name (*.aut) with directory path (e.g., /Users/fmi04/src-gen/bin/RV-Example.aut): " << '\n';
  std::string filename;
  
   std::ifstream tempFile("../temp.txt");
        	std::string observable_actions;
  
       // Check if temp.txt was opened successfully
       if (!tempFile.is_open()) {
           std::cout << "Failed to open temp.txt." << std::endl;
           exit(EXIT_FAILURE);
       }
  
       // Read the filename from temp.txt
       std::getline(tempFile, filename);
       std::getline(tempFile, observable_actions);
     //std::cout<<observable_actions_path<<'\n';
     tempFile.close();
  readFile.open(filename);
  if (!readFile.is_open()) {
       	 	exit(EXIT_FAILURE);
    	}
  
  
  std::vector<std::string> temp;
       // std::cout << "Please write a list of observable actions: (separated with comma)? " << '\n';
  
  
  
        //writeFile.open("/Users/fmi04/runtime-EclipseXtext/roomT_GitHub/src-gen/bin/ignoreList.txt", std::ofstream::out | std::ofstream::trunc);
        //writeFile.open("/Users/fmi04/runtime-EclipseXtext/roomT_GitHub/src-gen/bin/temp", std::ios_base::out|std::ios_base::in|std::ios_base::app);
        //writeFile << "A ignore list of labels of transitions (separated with comma) in which observable actions are ignored: "<< observable_actions << "\n";
        //observable_actions.append(",time");
        //observable_actions.append(",(");
  
        while(!readFile.eof()){
  
  	std::string line;
  	getline(readFile, line);
  	size_t startPoint, endPoint;
  
  	startPoint = line.find(",\"");
  	endPoint = line.find("\",");
  
  
  	std::string result = line.substr(startPoint+2,endPoint-startPoint-2);
  	//std::cout << result << "\n";
  
  
  
        	std::stringstream ss(observable_actions);
  	std::string substr;
  	int found = 0;
  	while(std::getline(ss, substr, ',')){
                if(result.find(substr) != std::string::npos){
                    found = 1;
                }
            }
  
  
  	int douplicated = 0;
  	if (found == 0){
               //std::cout << result << "\n";
               for(int i = 0; i < temp.size(); i++){
                if(temp[i].find(result) != std::string::npos){
                 	douplicated = 1;
              } 
  
            }
            if(douplicated == 0){
            temp.push_back(result);
            std::cout << result << "," << "\n";
            	}
           } 
  
        }
}

        
