/*
 * This file was autogenerated by the Lingua Franca Compiler.
 *
 * Source: file:/media/vboxuser/8a7cb2fb-d46a-4d79-9e91-c35c5f59a64a/MyExample%20(copy)/Tinification/Automate/extraction_function/extraction_function.lf
 */

#pragma once

#include <vector>
#include <array>

#include "reactor-cpp/reactor-cpp.hh"
// include the preambles from imported files 
#include "extraction_function/_lf_preamble.hh"

using namespace std::chrono_literals;

            
