/*
 * This file was autogenerated by the Lingua Franca Compiler.
 *
 * Source: file:/media/vboxuser/8a7cb2fb-d46a-4d79-9e91-c35c5f59a64a/MyExample%20(copy)/Tinification/Automate/castfunction_variables/castfunction_variables.lf
 */
 
#pragma once

#include "reactor-cpp/reactor-cpp.hh"
#include "lfutil.hh"

using namespace std::chrono_literals;

#include "castfunction_variables/_lf_preamble.hh"

        

// public preamble


class castfunction_variables: public reactor::Reactor {
public:
  struct Parameters {
        
  };

 private:
        

  class Inner: public lfutil::LFScope {
    [[maybe_unused]] const Inner& __lf_inner = *this;
    [[maybe_unused]] const Parameters __lf_parameters;
        
    // state variable
    std::vector<int> state_timeValue;
    std::vector<std::vector<std::string>> stateId_msg;
    int advancesTime;
    int cntShift;
    std::vector<std::vector<std::string>> stateId_varValue;
    std::vector<std::vector<std::string>> stateId_varName;
    std::vector<std::string> state_Id;
    std::vector<std::string> stateId;
    int index;
    // methods
    
    // reaction bodies
    void reaction_1([[maybe_unused]] const reactor::StartupTrigger& startup);
    // deadline handlers
    

    Inner(reactor::Reactor* reactor, Parameters&& parameters);

   friend castfunction_variables;
  };

  Inner __lf_inner;

  // parameter aliases for use in the outer scope
  // reactor instances
  // timers
  
  // actions
  
  // default actions
  reactor::StartupTrigger startup {"startup", this};
  reactor::ShutdownTrigger shutdown {"shutdown", this};
  // reaction views
  
  // reactions
  void reaction_1_body() { __lf_inner.reaction_1(startup); }
  reactor::Reaction reaction_1{"reaction_1", 1, this, [this]() { reaction_1_body(); }};

 public:
  // input ports
  
  // output ports
  
  castfunction_variables(const std::string& name, reactor::Environment* __lf_environment, Parameters&& __lf_parameters);
  castfunction_variables(const std::string& name, reactor::Reactor* __lf_container, Parameters&& __lf_parameters);

  void assemble() override;
};

        
