/*
 * This file was autogenerated by the Lingua Franca Compiler.
 *
 * Source: file:/home/ali123ata/Desktop/3/Tinification/extraction_function/extraction_function.lf
 */

#include "reactor-cpp/reactor-cpp.hh"

#include "extraction_function/_lf_preamble.hh"

using namespace std::chrono_literals;
using namespace reactor::operators;

            
