/*
 * This file was autogenerated by the Lingua Franca Compiler.
 *
 * Source: file:/home/ali123ata/Desktop/3/Tinification/extraction_function/extraction_function.lf
 */
 
#pragma once

#include "reactor-cpp/reactor-cpp.hh"
#include "lfutil.hh"

using namespace std::chrono_literals;

#include "extraction_function/_lf_preamble.hh"

        

// public preamble


class extraction_function: public reactor::Reactor {
public:
  struct Parameters {
        
  };

 private:
        

  class Inner: public lfutil::LFScope {
    [[maybe_unused]] const Inner& __lf_inner = *this;
    [[maybe_unused]] const Parameters __lf_parameters;
        
    // state variable
    
    // methods
    
    // reaction bodies
    void reaction_1([[maybe_unused]] const reactor::StartupTrigger& startup);
    // deadline handlers
    

    Inner(reactor::Reactor* reactor, Parameters&& parameters);

   friend extraction_function;
  };

  Inner __lf_inner;

  // parameter aliases for use in the outer scope
  // reactor instances
  // timers
  
  // actions
  
  // default actions
  reactor::StartupTrigger startup {"startup", this};
  reactor::ShutdownTrigger shutdown {"shutdown", this};
  // reaction views
  
  // reactions
  void reaction_1_body() { __lf_inner.reaction_1(startup); }
  reactor::Reaction reaction_1{"reaction_1", 1, this, [this]() { reaction_1_body(); }};

 public:
  // input ports
  
  // output ports
  
  extraction_function(const std::string& name, reactor::Environment* __lf_environment, Parameters&& __lf_parameters);
  extraction_function(const std::string& name, reactor::Reactor* __lf_container, Parameters&& __lf_parameters);

  void assemble() override;
};

        
